
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Albums</title>
</head>
<body>
    <h1>Liste des Albums</h1>
    <ul>
        <!-- à générer dynamiquemenet -->
        <?php foreach($albums as $album): ?>
            <li> 
                <?= $album["title"] ?> - <?=  $album['artiste'] ?> 
                <!-- /edit/id -->
                <a href="/edit?id=<?=$album["id"] ?>">Modifier</a>
                <!-- /delete/:id  -->
                <a href="/delete?id=<?= $album["id"] ?>">Supprimer</a>
        </li>
            <?php endforeach; ?>
    </ul>
    <h2>Ajouter un nouvel album</h2>
    <form action="/add" method="post">
        <input type="text" name="title" placeholder="Titre...">
        <input type="text" name="artiste" placeholder="Artiste">
        <input type="submit" value="Ajouter">
    </form>
</body>
</html>